//--------------------------------------------------------------------------------------------------------------------------------------------------
#define NUM_THREADS_X 8
#define NUM_THREADS_Y 8
#define NUM_THREADS_Z 8

//--------------------------------------------------------------------------------------------------------------------------------------------------
int3 resolution;
float3 rcpResolution;
RWTexture3D<float4> outputFloat4;

//--------------------------------------------------------------------------------------------------------------------------------------------------
float random(float3 v)
{
	return frac(sin(dot(v.xyz, float3(12.9898, 78.233, 159.351))) * 43758.5453123);
}

//--------------------------------------------------------------------------------------------------------------------------------------------------
float noise(float3 v)
{
	float3 i = floor(v);
	float3 f = frac(v);

	float3 t = f * f * (3.0 - 2.0 * f); // cubic hermite
	
	float x0y0z0 = random(i);
	float x1y0z0 = random(i + float3(1,0,0));
	float x0y1z0 = random(i + float3(0,1,0));
	float x1y1z0 = random(i + float3(1,1,0));
	float x0y0z1 = random(i + float3(0,0,1));
	float x1y0z1 = random(i + float3(1,0,1));
	float x0y1z1 = random(i + float3(0,1,1));
	float x1y1z1 = random(i + float3(1,1,1));

	float y0z0 = lerp(x0y0z0, x1y0z0, t.x);
	float y1z0 = lerp(x0y1z0, x1y1z0, t.x);
	float y0z1 = lerp(x0y0z1, x1y0z1, t.x);
	float y1z1 = lerp(x0y1z1, x1y1z1, t.x);

	float z0 = lerp(y0z0, y1z0, t.y);
	float z1 = lerp(y0z1, y1z1, t.y);

	return lerp(z0, z1, t.z);
}

//--------------------------------------------------------------------------------------------------------------------------------------------------
#pragma kernel CSMain
[numthreads(NUM_THREADS_X,NUM_THREADS_Y,NUM_THREADS_Z)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	float3 v = rcpResolution * id * 7.0;
	outputFloat4[id] = noise(v);
}
