//--------------------------------------------------------------------------------------------------------------------------------------------------
#define NUM_THREADS_X 8
#define NUM_THREADS_Y 8
#define NUM_THREADS_Z 8
#define NOISE_SCALE 3.0

//--------------------------------------------------------------------------------------------------------------------------------------------------
//#include "Assets/Raymarching/Shader/SimplexNoise3D.cginc"
//#include "Assets/Raymarching/Shader/Noise.cginc"
#include "Assets/Raymarching/Shader/WorleyNoise.cginc"

//--------------------------------------------------------------------------------------------------------------------------------------------------
int3 resolution;
float3 rcpResolution;
RWTexture3D<float4> outputFloat4;
float2 time;	// x=Time.deltaTime, y=Time.time

//--------------------------------------------------------------------------------------------------------------------------------------------------
#pragma kernel Init
[numthreads(NUM_THREADS_X,NUM_THREADS_Y,NUM_THREADS_Z)]
void Init(uint3 id : SV_DispatchThreadID)
{
	float3 v = rcpResolution * id * NOISE_SCALE;
	outputFloat4[id] = 1 - WorleyNoise(v);
}

//--------------------------------------------------------------------------------------------------------------------------------------------------
#pragma kernel Update
[numthreads(NUM_THREADS_X,NUM_THREADS_Y,NUM_THREADS_Z)]
void Update(uint3 id : SV_DispatchThreadID)
{
	float3 v = rcpResolution * id * NOISE_SCALE;
	outputFloat4[id] = 1 - WorleyNoise(v, time.y);
}
